name: 'Validate PR title'

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions: write-all

jobs:
  pr-title:
    runs-on: [self-hosted, test]
    container: ubuntu:latest

    name: 'Title'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            chore
            ci
            docs
            feat
            fix
            refactor
            revert
            style
            test
          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            starts with an uppercase character.
          wip: true
